#!/bin/bash

# Get the master PID of Gunicorn
master_pid=$(ps aux | grep '[g]unicorn' | grep 'master' | awk '{print $2}')

if [ -z "$master_pid" ]; then
    echo "Gunicorn is not running."
    exit 1
fi

# Gracefully reload Gunicorn
kill -HUP "$master_pid"

echo "Gunicorn has been reloaded gracefully."
