#!/usr/bin/env bash
# Gracefully restart Gunicorn by sending a HUP signal to the master process

MASTER_PID=$(ps -C gunicorn -o pid= | head -n 1)

if kill -HUP "$MASTER_PID"; then
    echo "OK"
else
    echo "NOk"
fi
